# Generated by Django 3.1.7 on 2021-02-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_lead_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attachment',
            field=models.FileField(null=True, upload_to='uploads/leads/'),
        ),
    ]
