# Generated by Django 3.1.7 on 2021-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20210825_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomessage',
            name='complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
