# Generated by Django 3.1.7 on 2021-08-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20210826_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotab',
            name='todos',
        ),
        migrations.AddField(
            model_name='todomessage',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.todotab'),
        ),
    ]
