# Generated by Django 3.1.7 on 2021-02-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_lead_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/leads/'),
        ),
    ]
